version: '3.9'

services:
  web:
    build: ./web_app
    ports:
      - "8080:8080"
    env_file:
      - .env


  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
