version: '3.9'

services:
  web:
    build: ./web_app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://fav:1111@cluster0.5hb4r.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
