services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  flask-app:
    build:
      context: ./web_app
    container_name: flask-app
    ports:
      - "5002:5002"  
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
