name: Web App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
      - name: Run tests with pytest
        run: |
          pipenv run pytest
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker Images
        run: |
          docker-compose -f docker-compose.yml push
      
  deploy:
    needs: docker
    steps:
      - name: Install doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.94.0/doctl-1.94.0-linux-amd64.tar.gz -o doctl.tar.gz
          tar -xzf doctl.tar.gz
          sudo mv doctl /usr/local/bin
          doctl version

      - name: Deploy to DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITAL_OCEAN }}
        run: |
          doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN
          doctl apps create --spec ./web_app/digitalocean-app-spec.yaml